ports:
  - port: 3000
    onOpen: open-preview
image:
  file: .gitpod.Dockerfile
tasks:
  - init: >
      bundle install --without production &&
      rails db:migrate
    command: >
      rails server
github:
    prebuilds:
        pullRequestsFromForks: true